# Generated by Django 5.0.4 on 2024-08-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0002_alter_orderpayment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
