# Generated by Django 5.0.4 on 2024-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0003_company_users_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número de caso')),
                ('client', models.CharField(max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service_description', models.TextField()),
                ('remarks', models.TextField()),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
    ]
