# Generated by Django 5.0.4 on 2024-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0004_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.CharField(default='', max_length=255, verbose_name='Cliente'),
        ),
    ]
