# Generated by Django 5.0.4 on 2024-08-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0004_orderpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
