# Generated by Django 5.0.4 on 2024-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0005_alter_workorder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='invesment',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Inversión'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(verbose_name='Observaciones del caso'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sales_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor de venta'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_description',
            field=models.TextField(verbose_name='Descripción del servicio'),
        ),
    ]
