# Generated by Django 5.0.4 on 2024-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0006_orderpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión')),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta')),
                ('service_description', models.TextField(verbose_name='Descripción del servicio')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Empresa')),
                ('account_owner', models.CharField(default='', max_length=255, verbose_name='Propietario de la cuenta')),
                ('bank_account', models.CharField(default='', max_length=255, verbose_name='Banco')),
                ('account_number', models.CharField(default='', max_length=255, verbose_name='Número de cuenta')),
                ('type_account', models.CharField(default='', max_length=255, verbose_name='Tipo de cuenta')),
                ('amount', models.IntegerField(verbose_name='Pago')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('made_by', models.CharField(max_length=255, verbose_name='Realizado por')),
                ('created_at', models.DateField(verbose_name='Creado el')),
                ('approved_at', models.DateField(auto_now_add=True, verbose_name='Rechazado el')),
                ('approved_by', models.CharField(max_length=255, verbose_name='Rechazado por')),
            ],
            options={
                'verbose_name': 'Pago aprobado',
                'verbose_name_plural': 'Pagos aprobados',
            },
        ),
        migrations.CreateModel(
            name='PaymentRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión')),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta')),
                ('service_description', models.TextField(verbose_name='Descripción del servicio')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Empresa')),
                ('account_owner', models.CharField(default='', max_length=255, verbose_name='Propietario de la cuenta')),
                ('bank_account', models.CharField(default='', max_length=255, verbose_name='Banco')),
                ('account_number', models.CharField(default='', max_length=255, verbose_name='Número de cuenta')),
                ('type_account', models.CharField(default='', max_length=255, verbose_name='Tipo de cuenta')),
                ('amount', models.IntegerField(verbose_name='Pago')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('made_by', models.CharField(max_length=255, verbose_name='Realizado por')),
                ('created_at', models.DateField(verbose_name='Creado el')),
                ('rejected_at', models.DateField(auto_now_add=True, verbose_name='Rechazado el')),
                ('rejected_by', models.CharField(max_length=255, verbose_name='Rechazado por')),
            ],
            options={
                'verbose_name': 'Pago rechazado',
                'verbose_name_plural': 'Pagos rechazados',
            },
        ),
    ]
