# Generated by Django 5.0.4 on 2024-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0006_alter_workorder_invesment_alter_workorder_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='invesment',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(null=True, verbose_name='Observaciones del caso'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sales_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta'),
        ),
    ]
