# Generated by Django 5.0.4 on 2024-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0007_alter_workorder_invesment_alter_workorder_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='in_charge',
            field=models.CharField(default='', max_length=255, verbose_name='Encargado'),
        ),
    ]
