# Generated by Django 5.0.4 on 2024-08-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0010_alter_affiliation_affiliation_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('since', models.DateField(verbose_name='Desde')),
                ('up_to', models.DateField(verbose_name='Hasta')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('created_by', models.CharField(max_length=255, verbose_name='Realizado por')),
                ('created_at', models.DateField(verbose_name='Realizado el')),
                ('affiliation_cost', models.DecimalField(decimal_places=2, default=96700.0, max_digits=20, verbose_name='Costo de afiliación')),
                ('rejected_at', models.DateField(auto_now_add=True, verbose_name='Rechazado el')),
                ('rejected_by', models.CharField(max_length=255, verbose_name='Rechazado por')),
            ],
            options={
                'verbose_name': 'Afiliación rechazada',
                'verbose_name_plural': 'Afiliaiciones rechazadas',
            },
        ),
    ]
