# Generated by Django 5.0.4 on 2024-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0010_alter_workorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='order_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número de caso'),
        ),
    ]
