# Generated by Django 5.0.4 on 2024-08-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0011_alter_workorder_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
