# Generated by Django 5.0.4 on 2024-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0012_delete_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión')),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta')),
                ('service_description', models.TextField(verbose_name='Descripción del servicio')),
                ('remarks', models.TextField(null=True, verbose_name='Observaciones del caso')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('assigned_by', models.CharField(default='', max_length=255, verbose_name='Asignado por')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
    ]
