# Generated by Django 5.0.4 on 2024-08-06 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0014_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Asignado el'),
            preserve_default=False,
        ),
    ]
