# Generated by Django 5.0.4 on 2024-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0016_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Empresa'),
        ),
    ]
