# Generated by Django 5.0.4 on 2024-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0016_alter_orderpayment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='comments',
            field=models.TextField(default='SIN COMENTARIOS', verbose_name='Comentarios'),
        ),
    ]
