# Generated by Django 5.0.4 on 2024-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0017_workorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.CharField(default='', max_length=255, verbose_name='Empresa'),
        ),
    ]
