# Generated by Django 5.0.4 on 2024-08-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0019_finishedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinishedOrder',
        ),
    ]
