# Generated by Django 5.0.4 on 2024-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0021_finishedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedOrder',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión')),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta')),
                ('service_description', models.TextField(verbose_name='Descripción del servicio')),
                ('remarks', models.TextField(null=True, verbose_name='Observaciones del caso')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('assigned_by', models.CharField(default='', max_length=255, verbose_name='Asignado por')),
                ('status', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('deleted_at', models.DateField(auto_now_add=True, verbose_name='Eliminado el')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Empresa')),
                ('deleted_by', models.CharField(default='', max_length=255, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Caso eliminado',
                'verbose_name_plural': 'Casos eliminados',
            },
        ),
    ]
