# Generated by Django 5.0.4 on 2024-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0023_invoicedorder_alter_deletedorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Número de caso')),
                ('client', models.CharField(default='', max_length=255, verbose_name='Cliente')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('invesment', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Inversión')),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Valor de venta')),
                ('service_description', models.TextField(verbose_name='Descripción del servicio')),
                ('in_charge', models.CharField(default='', max_length=255, verbose_name='Encargado')),
                ('company', models.CharField(default='', max_length=255, verbose_name='Empresa')),
                ('amount', models.IntegerField(verbose_name='Pago')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('made_by', models.CharField(max_length=255, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
