# Generated by Django 5.0.4 on 2024-08-11 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0024_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Creada el'),
        ),
    ]
