# Generated by Django 5.0.4 on 2024-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0025_orderpayment_created_at_alter_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='account_owner',
            field=models.CharField(default='', max_length=255, verbose_name='Propietario de la cuenta'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='bank_account',
            field=models.CharField(default='', max_length=255, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='type_account',
            field=models.CharField(default='', max_length=255, verbose_name='Tipo de cuenta'),
        ),
    ]
