# Generated by Django 5.0.4 on 2024-08-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0026_orderpayment_account_owner_orderpayment_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombres y apellidos')),
                ('type_document', models.CharField(max_length=255, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=255, verbose_name='Número de documento')),
                ('bank_account', models.CharField(max_length=255, verbose_name='Banco')),
                ('account_number', models.CharField(max_length=255, verbose_name='Número de cuenta')),
                ('type_account', models.CharField(max_length=255, verbose_name='Tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='account_number',
            field=models.CharField(default='', max_length=255, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='bank_account',
            field=models.CharField(default='', max_length=255, verbose_name='Banco'),
        ),
    ]
