# Generated by Django 5.0.4 on 2024-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMWEB', '0027_worker_orderpayment_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.CharField(default='', max_length=255, verbose_name='Empresa'),
        ),
    ]
